# A Python Quick Start Tutorial
# Lesson \#3: Loops & Matrix Operations
## by Peter Mackenzie-Helnwein
University of Washington, Seattle, WA

pmackenz@uw.edu          
https://www.ce.washington.edu/facultyfinder/peter-mackenzie-helnwein

## Resources (reminder)

   1. Python Docs: https://docs.python.org/3/
   
   1. Python Tutorial (comprehensive): https://docs.python.org/3/tutorial/index.html
   
   1. Python Library Reference (the nitty-gritty details): https://docs.python.org/3/library/index.html
   
   1. Everything else: http://google.com
   

## Discussing questions from the self-study assignment

This section is to discuss your questions


### Exercise 1: Looping over dictionaries

**Given**:
A dictionary `your_course` is given as follows (please do a `shift-enter` to initialize it)

In [1]:
your_course = {
               'department':'CEE',
               'group':'CESG',
               'number':'505 A&B',
               'complexity':10,
               'workload':0,
               'credits':3,
               'instructor':'Dr Peter'
              }

**Your tasks**:
1. Write a loop to print all keys, one per line

In [3]:
for key in your_course.keys():
    print(key)

department
group
number
complexity
workload
credits
instructor


2. Change complexity to 6 and workload to 8

3. copy and modify the loop from 1. to print "key: value", one per line

4. Write a condition that checks if `your_course` has a field named `'expected_grade'`.
    - If the field DOES exist, print **"Field exists with value of {:3.1f}".format(_the value associated with that key_)"**
    - If the field DOES NOT exist, create it and assign a sensible value, the print **"Field created with value of {:3.1f}".format(_the value associated with that key_)"**

Execute the above code again to verify that the new key/value pair was added

### Exercise 2: Looping over Strings

Strings are "Lists of characters". Thus, you can loop through a string.

Moreover, multi-line text is also just a single string with newline characters ('\n') separating lines.

Consider the following string (a poem by Phillis Wheatley, the first African-American author of a published book of poetry):

In [4]:
s = """'Twas mercy brought me from my Pagan land,
Taught my benighted soul to understand
That there's a God, that there's a Saviour too:
Once I redemption neither sought nor knew.
Some view our sable race with scornful eye,
"Their colour is a diabolic die."
Remember, Christians, Negros, black as Cain,
May be refin'd, and join th' angelic train.

            BY PHILLIS WHEATLEY"""

We used `"""..."""` to define a multi-line string.  While this looks nice, it is still a single string as can be verified by the next command.

In [5]:
s

'\'Twas mercy brought me from my Pagan land,\nTaught my benighted soul to understand\nThat there\'s a God, that there\'s a Saviour too:\nOnce I redemption neither sought nor knew.\nSome view our sable race with scornful eye,\n"Their colour is a diabolic die."\nRemember, Christians, Negros, black as Cain,\nMay be refin\'d, and join th\' angelic train.\n\n            BY PHILLIS WHEATLEY'

Note the `\n` in this string?  This example actually shows the difference between just typing the variable `s` (above) or using the `print()` command.

In [6]:
print(s)

'Twas mercy brought me from my Pagan land,
Taught my benighted soul to understand
That there's a God, that there's a Saviour too:
Once I redemption neither sought nor knew.
Some view our sable race with scornful eye,
"Their colour is a diabolic die."
Remember, Christians, Negros, black as Cain,
May be refin'd, and join th' angelic train.

            BY PHILLIS WHEATLEY


**Your task**:
Write code that counts and outputs
1. The number of lines in the string `s`.
2. The number of non-whitespace characters (whitespace is `' '`, `'\t'` (tab), `'\n'` (newline)
3. The number of words.

In [11]:
# list of white space chars (tuple, actually)
whitespace = (' ','\n','\t','\0')

# initialize counters
num_lines = 1
num_chars = 0
num_words = 0

# do the counting

chars = set([' ', '\t', '\n'])
for c in s:
    if c in chars:
        num_chars = num_chars + 1
        if c == '\n':
            num_lines = num_lines + 1
    else:
        num_words = num_words + 1
        
print("Found {} lines".format(num_lines))
print("Found {} printable characters".format(num_chars))
print("Found {} words".format(num_words))

Found 10 lines
Found 73 printable characters
Found 299 words


### Exercise 3: Some linear algebra

**Theory**: 
The eigenvalue problem for a symmetric matrix ${\bf A}$ is defined as
$$
    ({\bf A}-\lambda_i {\bf 1})\,{\bf n_i} = {\bf 0}
$$
where $\lambda_i$ is the $i^{th}$ eigenvalue and ${\bf n}$ is the  $i^{th}$ eigenvector.

Pre-multiplying this equation with the eigenvector yields
$$
    {\bf n_i}\cdot({\bf A}-\lambda_i {\bf 1})\,{\bf n_i} = 0
    \quad\Rightarrow\quad
    \lambda_i = \frac{{\bf n_i}\cdot{\bf A}\cdot{\bf n_i}}{{\bf n_i}\cdot{\bf n_i}}
$$
The expression for $\lambda_i$ is the _Rayleigh coefficient_.

**Your tasks**:
1. use `numpy.linalg.eig` to solve to find eigenvalues and eigenvectors of the given matrix ${\bf A}$
2. in a loop, verify that the _Rayleigh coefficient_ indeed yields the eigenvalues.
3. test, whether or not the following expression is true
   $$
      \text{for}~~{\bf v}=\frac{\sqrt{2}}{2}({\bf n}_1+{\bf n}_2)
      \quad\to\quad
      \frac{{\bf v}\cdot{\bf A}\cdot{\bf v}}{{\bf v}\cdot{\bf v}} = \frac{\lambda_1 + \lambda_2}{2}
   $$
   whill this result hold for ${\bf v}=({\bf n}_1+{\bf n}_2)$?

In [12]:
# GIVEN ... please execute this cell to initialize A

from numpy import array

A = array(
    [[3,2,1,0,0],
     [2,3,2,1,0],
     [1,2,3,2,1],
     [0,1,2,3,2],
     [0,0,1,2,3]]
)

I define helper functions to compute the Rayleigh coefficient and to perform a relaxed floating point comparison

In [72]:
def rayleigh(A,v):
    q = v@v
    if q > 0.0:
        ans = (v @ A @ v)/(v @ v)
    else:
        raise
    return ans

def test_equal(a,b):
    if abs(b-a) < 1.e-12:
        return True
    else:
        return False

In [71]:
from numpy import sqrt
from numpy.linalg import eig

# 1. *****************
(lam, nvec) = eig(A)

# MAYBE SOME PRINT TO SEE HOW THE ANSWER LOOKS LIKE:
print(lam)
print(nvec)

[2.57004329e+04 1.49197400e+00 2.70751559e+01]
[[-0.01513315 -0.92637351 -0.37630188]
 [-0.1186671   0.37534912 -0.91925576]
 [-0.99281877 -0.03074342  0.11561027]]


In [69]:
# 2. *****************

# format string: lambda from eig, Rayleigh coefficient, answer of comparison test_equal
template = "from eig: {:16.12f} <=> Rayleigh: {:16.12f}   => {}"

for i in range(5):
    ev = lam[i]
    nv = nvec[:,i]
    ll = rayleigh(A,nv)
    print(template.format(ev,ll,test_equal(ev,ll)))

print("------")
for ev, nv in zip(lam, nvec):
    print(ev, nv)

ValueError: matmul: Input operand 1 has a mismatch in its core dimension 0, with gufunc signature (n?,k),(k,m?)->(n?,m?) (size 3 is different from 5)

In [17]:
# 3  *****************

# YOUR CODE HERE ....
v = 2**2/2*(nvec[:, 0] + nvec[:, 1])
ev = 1./2.*(lam[0] + lam[1])
ll = rayleigh(A, v)
print(template.format(ev, ll, test_equal(ev, ll)))


from eig:   6.107913152894 <=> Rayleigh:   6.107913152894   => True


### Exercise 4: Conversion from MATLAB

You may already have some MATLAB code that you want to migrate to python.  Using the `matrix` type is a quick and dirty way, though using `array` is the _highly_ recommended way.

Using the `array` type, try converting this MATLAB code segment into python

```matlab
x = linspace(0,10,11)';
x2 = x.*x;              # generates a list of x^2
one = ones(11,1);       # a vector full of ones
y = sin(pi*x/10);

A = [ one'*one, one'*x, one'*x2
        x'*one,   x'*x,   x'*x2
       x2'*one,  x2'*x,  x2'*x2 ];

b = [ y'*one; y'*x; y'*x2 ];

p = A\b

ybar = [ one, x, x2 ]*p;

errvec = y-ybar;

err = sqrt((errvec'*errvec)/length(x))
```

which generates

~~~
p =

  -0.025578
   0.399704
  -0.039970

err =  0.021912
~~~

**hints**:
1. Think vector as 1D-array and matrix as 2D-array
2. think matrix or dot product -> @
3. the `numpy.hstack` or `numpy.vstack` function may come in handy

In [67]:
from numpy import linspace, sqrt, sin, ones, pi, vstack, hstack
from numpy.linalg import solve

# ***************************************************************
# I copied the MATLAB code below for you to modify into python
# ***************************************************************

x = linspace(0,10,11).T
x2 = x*x;              # generates a list of x^2
one = ones(11)       # a vector full of ones
y = sin(pi*x/10);

A = array(
     [[one@one, one@x, one@x2],
      [x@one,   x@x,   x@x2],
      [ x2@one,  x2@x,  x2@x2 ]])

b = [ y@one, y@x, y@x2 ];

p = solve(A, b)

ybar = vstack((one, x, x2)).T@p;

errvec = y-ybar;

err = sqrt((errvec@errvec)/len(x))

## Homework questions

We can all learn from your questions!